import type { Metadata } from "next";
import "./globals.css";
import {Oswald } from "next/font/google";
import { cn } from "@/lib/utils";
import localFont from "next/font/local";

const helveticaNow = localFont({
  src: [
    {
      path: "../public/fonts/helvetica/helveticanowtext-black-demo.ttf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-helvetica-now",
});
const garet = localFont({
  src: [
    {
      path: "../public/fonts/garet_woff2/Garet-Thin.woff2",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-helvetica-now",
})
const oswald = Oswald({
  subsets: ['latin'],
})


export const metadata: Metadata = {
  title: "Wellness Gym",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
    // style={{ fontFamily: "var(--font-helvetica-now)",
      
    //  }}
      className={cn("h-full", "antialiased", "font-sans")}
    >
      <body className="min-h-full flex flex-col ">{children}</body>
    </html>
  );
}
